
name: Build and Test an .NET App

on:
  push:
    branches: [ "develop", "feature"  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout .Net
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build only
      run: dotnet build --no-restore
      
    - name: Run Unit and Integration Test
      run: dotnet test --no-build --verbosity normal
